apiVersion: v1
kind: Service
metadata:
  name: actionapiservice
  labels:
    app: actionapiservice
  namespace: services
spec:
  ports:
    - port: 8080
  selector:
    app: actionapiservice
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: actionapiservice
  labels:
    app: actionapiservice
  namespace: services
spec:
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: actionapiservice
    spec:
      containers:
      - name: actionapiservice
        image: exorath/actionapiservice
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: REDIS_URI
          value: "<INSERT_URI>"